Task 1
willianmga/hello-microservices pull request #20
Opened 2017-06-05 18:26 UTC by willianmga

Created all the architecture of project
Mapped all the dependencies
Created endpoint to create persons into middle project
Created endpoint to find persons by id into middle project
Created the request and response classes into core project

2017-06-05 18:31 UTC, rochapaulo requested changes
Remove all eclipse config files.

2017-06-05 18:49 UTC, rochapaulo reviewed
Provide automated tests for each endpoint, consider:
jUnit4 and RestAssured

http://rest-assured.io/
http://junit.org/junit4/

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-core/src/main/java/matera/com/hellomicroservices/core/requests/CreatePersonRequest.java
> +public class CreatePersonRequest {
- Coding standard: always put an empty line between attributes and methods declaration
- Use tabspace = 4, seems that your code is using 8 (check how to configure your IDE)

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-core/src/main/java/matera/com/hellomicroservices/core/responses/AddressResource.java
> +	private String city;
same pointed above

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-core/src/main/java/matera/com/hellomicroservices/core/responses/PersonResource.java
> +	@XmlElement(name = "uuid")
same pointed above (coding standard and tabspace)

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/converter/PersonConverter.java
> +	public static AddressResource convertToAddressResource(Address address) {
Move this to it's specific class, let's follow SRP principle

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/entities/Address.java
> +public class Address {
refactor this to use Builder pattern. 

usage example:

`Address addr = Address.builder()
.withCity(...)
.withState(...)
.withCountry(...)
.withZipcode(...)
.build()`

the build method should validate the fields value and format (if needed), set all attributes as final and block direct instantiation, force construction through its builder.

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/entities/Person.java
> +public class Person implements Serializable {
- same pointed above
- you don't need serializable here

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/rest/HelloRS.java
> +	/*@GET
remove commented code

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/rest/PersonRS.java
> +		String location = "/persons/" + String.valueOf(response.getId());
don't think you need String.valueOf here as its id will never be null, you can concatenate it directly.

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/rest/PersonRS.java
> +		return Response.ok(new ArrayList<PersonResource>()).build();
call a service to list all the persons

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/rest/PersonRS.java
> +		PersonResource resource = service.findByUUID(UUID.fromString(userUUID));
what happens if the user is not found? let's change the code to answer with 404 for this scenario

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/service/PersonService.java
> +		Person inserted = store.insert(person);
what happens in case of error? lets handle it and put the proper message on response object

2017-06-05 18:49 UTC, rochapaulo commented on hello-microservices-middle/src/main/java/com/matera/hellomicroservices/service/PersonService.java
> +		Person found = store.getById(uuid);
please, handle the case where no resource is found for given UUID

2017-06-06 14:18 UTC, willianmga reviewed
i've just finished implementing the reviews you requested.

2017-06-07 17:53 UTC, merged